/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(lora_frame_detector_single_sf.h) */
/* BINDTOOL_HEADER_FILE_HASH(d05a9bfedcdbf7523356b4e5080509d8) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cran/lora_frame_detector_single_sf.h>
// pydoc.h is automatically generated in the build directory
#include <lora_frame_detector_single_sf_pydoc.h>

void bind_lora_frame_detector_single_sf(py::module &m) {

  using lora_frame_detector_single_sf =
      ::gr::cran::lora_frame_detector_single_sf;

  py::class_<lora_frame_detector_single_sf, gr::block, gr::basic_block,
             std::shared_ptr<lora_frame_detector_single_sf>>(
      m, "lora_frame_detector_single_sf", D(lora_frame_detector_single_sf))

      .def(py::init(&lora_frame_detector_single_sf::make), py::arg("samp_rate"),
           py::arg("sf"), D(lora_frame_detector_single_sf, make))

      ;
}
