/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(lora_frame_sync.h) */
/* BINDTOOL_HEADER_FILE_HASH(3591e9cbf3f63ff13ea0cf874ee345b5) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cran/lora_frame_sync.h>
// pydoc.h is automatically generated in the build directory
#include <lora_frame_sync_pydoc.h>

void bind_lora_frame_sync(py::module &m) {

  using lora_frame_sync = ::gr::cran::lora_frame_sync;

  py::class_<lora_frame_sync, gr::block, gr::basic_block,
             std::shared_ptr<lora_frame_sync>>(m, "lora_frame_sync",
                                               D(lora_frame_sync))

      .def(py::init(&lora_frame_sync::make), py::arg("center_freq"),
           py::arg("bandwidth"), py::arg("sf"), py::arg("impl_head"),
           py::arg("sync_word"), py::arg("os_factor"),
           py::arg("preamble_len") = 8, D(lora_frame_sync, make))

      ;
}
