/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rx_combining.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d8b69ea72d80f381df81637568aa302c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cran/rx_combining.h>
// pydoc.h is automatically generated in the build directory
#include <rx_combining_pydoc.h>

void bind_rx_combining(py::module& m)
{

    using rx_combining    = gr::cran::rx_combining;


    py::class_<rx_combining, gr::block, gr::basic_block,
        std::shared_ptr<rx_combining>>(m, "rx_combining", D(rx_combining))

        .def(py::init(&rx_combining::make),
           D(rx_combining,make)
        )
        



        ;




}








