/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(utilities.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ec5402bac0aa97445b0bd0401ccf858a) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cran/utilities.h>
// pydoc.h is automatically generated in the build directory
#include <utilities_pydoc.h>

void bind_utilities(py::module &m) {

  py::enum_<::gr::cran::Header_type>(m, "Header_type")
      .value("STREAMING", ::gr::cran::Header_type::STREAMING)       // 0
      .value("NEW_FRAME", ::gr::cran::Header_type::NEW_FRAME)       // 1
      .value("END_OF_FRAME", ::gr::cran::Header_type::END_OF_FRAME) // 2
      .export_values();

  py::implicitly_convertible<int, ::gr::cran::Header_type>();

  m.def("get_ip", &::gr::cran::get_ip, py::arg("interface"), D(get_ip));

  m.def("rev_endian", &::gr::cran::rev_endian, py::arg("number"),
        D(rev_endian));

  m.def("build_upchirp", &::gr::cran::build_upchirp, py::arg("chirp"),
        py::arg("id"), py::arg("sf"), py::arg("os_factor") = 1,
        D(build_upchirp));
}
