/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(zmq_dealer_sink.h) */
/* BINDTOOL_HEADER_FILE_HASH(84689c2165683e5281c63c1c19674362) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/cran/zmq_dealer_sink.h>
// pydoc.h is automatically generated in the build directory
#include <zmq_dealer_sink_pydoc.h>

void bind_zmq_dealer_sink(py::module &m) {

  using zmq_dealer_sink = ::gr::cran::zmq_dealer_sink;

  py::class_<zmq_dealer_sink, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<zmq_dealer_sink>>(m, "zmq_dealer_sink",
                                               D(zmq_dealer_sink))

      .def(py::init(&zmq_dealer_sink::make), D(zmq_dealer_sink, make))

      ;
}
