/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_sync_v2.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0a1252256b231d213e1f637d404dcddc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/lora_sdr/frame_sync_v2.h>
// pydoc.h is automatically generated in the build directory
#include <frame_sync_v2_pydoc.h>

void bind_frame_sync_v2(py::module& m)
{

    using frame_sync_v2    = gr::lora_sdr::frame_sync_v2;


    py::class_<frame_sync_v2, gr::block, gr::basic_block,
        std::shared_ptr<frame_sync_v2>>(m, "frame_sync_v2", D(frame_sync_v2))

        .def(py::init(&frame_sync_v2::make),
           D(frame_sync_v2,make)
        )
        



        ;




}








